name: repo_viewer
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.0.3
  webview_flutter: ^3.0.4
  flash: ^2.0.3+2
  auto_route: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  auto_route_generator: ^4.2.0

flutter:
  uses-material-design: true
